.gitignore
docker-compose.yml
src/main/java/com/sparta/mypet/MypetApplication.java
src/main/java/com/sparta/mypet/common/Timestamped.java
src/main/java/com/sparta/mypet/domain/auth/UserRepository.java
src/main/java/com/sparta/mypet/domain/auth/entity/User.java
src/main/java/com/sparta/mypet/domain/auth/entity/UserRoleEnum.java
src/main/java/com/sparta/mypet/domain/auth/entity/UserStatusEnum.java
src/main/java/com/sparta/mypet/domain/comment/CommentRepository.java
src/main/java/com/sparta/mypet/domain/comment/entity/Comment.java
src/main/java/com/sparta/mypet/domain/like/LikeRepository.java
src/main/java/com/sparta/mypet/domain/like/entity/Like.java
src/main/java/com/sparta/mypet/domain/post/PostRepository.java
src/main/java/com/sparta/mypet/domain/post/entity/File.java
src/main/java/com/sparta/mypet/domain/post/entity/Post.java
src/main/java/com/sparta/mypet/domain/report/ReportRepository.java
src/main/java/com/sparta/mypet/domain/report/entity/Report.java
src/main/java/com/sparta/mypet/domain/report/entity/ReportStatus.java
src/main/resources/application.properties

#1 
code with me를 통한 프로젝트 기본 세팅
docker-compose.yml
application.properties
entity
repository
>

[2024/07/19]feat/#1 project settings

---

src/main/java/com/sparta/mypet/common/dto/DataResponseDto.java
src/main/java/com/sparta/mypet/common/dto/MessageResponseDto.java
src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/common/entity/Timestamped.java
src/main/java/com/sparta/mypet/common/util/ResponseFactory.java
src/main/java/com/sparta/mypet/domain/auth/entity/User.java
src/main/java/com/sparta/mypet/domain/comment/entity/Comment.java
src/main/java/com/sparta/mypet/domain/post/entity/Post.java
src/main/java/com/sparta/mypet/domain/report/entity/Report.java

#9 
- MessageResponseDto 생성
- DataResponseDto 생성
- GlobalMessage 생성
- ResponseFactory 생성
>
컨트롤러의 API 리턴 응답은 ResponseFactory의 메서드를 이용하고, 응답 메세지는 GlobalMessage에 추가해서 사용하면 됩니다!

[2024/07/20] feat/#9 common response

---

src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java

#11 
- common 패키지 하위에 exception 패키지 생성
- exception 패키지 하위에 GlobalExceptionHandler 생성 및 구현 
>
새로운 Custom Exception이 생기면 GlobalExceptionHandler 클래스에 IllegalArgumentException을 참고해서 추가해 주시면 됩니다!

[2024/07/21] feat/#11 exception handler

---

src/main/java/com/sparta/mypet/domain/comment/CommentController.java
src/main/java/com/sparta/mypet/domain/comment/CommentRepository.java
src/main/java/com/sparta/mypet/domain/comment/CommentService.java
src/main/java/com/sparta/mypet/domain/comment/dto/CommentResponseDto.java

> #3 
> CommentController에 getComments 함수 작성
> CommentService에 getComments 함수 작성
> CommentRepository에 postId를 통해 댓글을 찾는 함수 작성

[2024/07/21]feat/#3 get comments

---

src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
src/main/java/com/sparta/mypet/common/exception/PostNotFoundException.java
src/main/java/com/sparta/mypet/domain/comment/CommentController.java
src/main/java/com/sparta/mypet/domain/comment/CommentService.java
src/main/java/com/sparta/mypet/domain/comment/dto/CommentRequestDto.java
src/main/java/com/sparta/mypet/domain/comment/dto/CommentResponseDto.java

> #4 [Feat] 댓글 생성
> CommentController에 createComment 함수 작성
> CommentService에 createComment 함수 작성
> GlobalExceptionHandler 정리

[2024/07/21]feat/#4 create comment

---

src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/common/exception/CommentNotFoundException.java
src/main/java/com/sparta/mypet/common/util/ResponseFactory.java
src/main/java/com/sparta/mypet/domain/comment/CommentController.java
src/main/java/com/sparta/mypet/domain/comment/CommentService.java

> #5
> deleteComment 추가
> CommentService에 getUserBy, getPostBy 함수들을 find로 변경
> ResponseFactory 수정
> CommentNotFoundException 추가
> ResponseFactory에 Null보다 Void가 type-safe하다고 알고있어서 수정했는데 혹시 제가 알고있으면 댓글로 알려주시면 감사하겠습니다.
> deleteComment URL을 변경했습니다. postId가 크게 필요하지않아보여서 변경했는데 이상하다싶으면 댓글로 알려주시면 감사하겠습니다.

[2024/07/22]feat/#5 delete comment

---

src/main/java/com/sparta/mypet/domain/comment/dto/CommentRequestDto.java
src/main/java/com/sparta/mypet/domain/like/LikeController.java
src/main/java/com/sparta/mypet/domain/like/LikeService.java

[2024/07/22]feat/#6 create like

---

src/main/java/com/sparta/mypet/domain/post/PostController.java
src/main/java/com/sparta/mypet/domain/post/PostService.java
src/main/java/com/sparta/mypet/domain/post/dto/PostResponseDto.java

[2024/07/22] feat/#21 post delete

---

src/main/java/com/sparta/mypet/domain/post/PostController.java
src/main/java/com/sparta/mypet/domain/post/PostService.java
src/main/java/com/sparta/mypet/domain/post/dto/PostResponseDto.java

> ex) #22 
> 게시글 전체 조회 API를 작성했습니다.
> page의 default값이 1로 시작합니다. controller에서 page-1을 해주고, service로 넘겨줍니다.

[2024/07/22] feat/#22 get posts

---

src/main/java/com/sparta/mypet/common/util/PaginationUtil.java
src/main/java/com/sparta/mypet/domain/comment/CommentController.java
src/main/java/com/sparta/mypet/domain/comment/CommentRepository.java
src/main/java/com/sparta/mypet/domain/comment/CommentService.java
src/main/java/com/sparta/mypet/domain/comment/dto/CommentPageResponse.java

> ex) #35
> 댓글 페이지네이션
> 페이지네이션 유틸 클래스 제작
> 페이지네이션 유틸 클래스를 제작했는데 Post 쪽에도 사용할만한지 검토 부탁드려요
> Controller에 전달하는 pagination 관련 변수명들도 API 명세에 적어둔 대로 이름을 맞췄습니다.

[2024/07/22] feat/#35 comment page

---

src/main/java/com/sparta/mypet/domain/post/PostController.java
src/main/java/com/sparta/mypet/domain/post/PostService.java
src/main/java/com/sparta/mypet/domain/post/dto/PostResponseDto.java

> ex) #23
> 게시물의 단건 조회 API를 작성했습니다.
> 페이지네이션 유틸이 넘어오면 Post의  페이지네이션도 리팩토리 예정입니다.

[2024/07/22] feat/#23 get post

---

src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
src/main/java/com/sparta/mypet/common/exception/custom/LikeNotFoundException.java
src/main/java/com/sparta/mypet/domain/like/LikeController.java
src/main/java/com/sparta/mypet/domain/like/LikeRepository.java
src/main/java/com/sparta/mypet/domain/like/LikeService.java

> #7
> 좋아요 취소 작업
> GlobalExceptionHandler 수정

[2024/07/22] feat/#7 delete like

---

src/main/java/com/sparta/mypet/domain/post/PostController.java
src/main/java/com/sparta/mypet/domain/post/PostService.java

> ex) #39 
> 기존 페이지네이션 Util 클래스를 사용하여 수정했습니다.

[2024/07/22] refactor/#39 refactor post

---

build.gradle
src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
src/main/java/com/sparta/mypet/common/exception/custom/CommentNotFoundException.java
src/main/java/com/sparta/mypet/common/exception/custom/PasswordInvalidException.java
src/main/java/com/sparta/mypet/common/exception/custom/PostNotFoundException.java
src/main/java/com/sparta/mypet/common/exception/custom/UserEmailDuplicateException.java
src/main/java/com/sparta/mypet/common/exception/custom/UserMisMatchException.java
src/main/java/com/sparta/mypet/common/initialization/DataInitialization.java
src/main/java/com/sparta/mypet/domain/auth/AuthController.java
src/main/java/com/sparta/mypet/domain/auth/AuthService.java
src/main/java/com/sparta/mypet/domain/auth/UserService.java
src/main/java/com/sparta/mypet/domain/auth/dto/LoginRequestDto.java
src/main/java/com/sparta/mypet/domain/auth/entity/User.java
src/main/java/com/sparta/mypet/domain/comment/CommentService.java
src/main/java/com/sparta/mypet/domain/like/LikeService.java
src/main/java/com/sparta/mypet/domain/post/PostService.java
src/main/java/com/sparta/mypet/security/JwtService.java
src/main/java/com/sparta/mypet/security/UserDetailsImpl.java
src/main/java/com/sparta/mypet/security/UserDetailsServiceImpl.java
src/main/java/com/sparta/mypet/security/config/JwtConfig.java
src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java
src/main/java/com/sparta/mypet/security/filter/JwtAuthorizationFilter.java
src/main/java/com/sparta/mypet/security/util/JwtProvider.java
src/main/resources/application.properties

#25 
- 시큐리티 전반적인 내용
- 로그인 기능 구현
-로그인 성공
>
로그인 없이 요청되는 API는 WebSecurityConfig에 requestMatchers 항목으로 추가해주세요!

[2024/07/23]feat/#25 security login

---

http-client.env.json
src/main/java/com/sparta/mypet/domain/comment/CommentController.java
src/main/java/com/sparta/mypet/domain/like/LikeController.java
src/main/java/com/sparta/mypet/domain/like/entity/Like.java
src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java
test.http

>#45
> 테스트 코드 추가
> Like에 RestController 추가
> CommentController : UserDetailsImpl로 변경
> Like : Sequence -> Identity로 변경
> WebSecurityConfig : posts/** 관련 GET 요청 허용

[2024/07/23]fix/#45 like bugfix

---

http/post.http
http/user.http
src/main/java/com/sparta/mypet/domain/post/PostController.java
src/main/java/com/sparta/mypet/domain/post/PostService.java
src/main/java/com/sparta/mypet/domain/post/dto/PostResponseDto.java

> ex) #49 
> 로그인한 사용자가 본인이 좋아요 누른 게시물을 단건 조회할 경우 isLike true 반환

[2024/07/23] fix/#49 postResponseDto isLike

---

http/user.http
src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
src/main/java/com/sparta/mypet/common/exception/custom/RefreshTokenInvalidException.java
src/main/java/com/sparta/mypet/domain/auth/AuthController.java
src/main/java/com/sparta/mypet/domain/auth/AuthService.java
src/main/java/com/sparta/mypet/security/JwtService.java
src/main/java/com/sparta/mypet/security/TokenType.java
src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java
src/main/java/com/sparta/mypet/security/filter/JwtAuthorizationFilter.java
src/main/java/com/sparta/mypet/security/util/JwtProvider.java

#31 
- Access 토큰 만료되면, refresh 토큰을 통해 Access 토큰, Refresh 토큰 재발급
>

[2024/07/23]feat/#31 refresh access token

---

http/user.http
src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/domain/auth/UserController.java
src/main/java/com/sparta/mypet/domain/auth/UserService.java
src/main/java/com/sparta/mypet/domain/auth/dto/UserWithPostListResponseDto.java
src/main/java/com/sparta/mypet/domain/auth/entity/User.java
src/main/java/com/sparta/mypet/domain/post/dto/PostMappedUserResponseDto.java

#30 
- 마의 페이지 정보를 위한, 자신의 게시물이 포함된 회원 단건 조회 기능 구현
>

[2024/07/24]feat/#30 get user

---

http/report.http
src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/domain/auth/UserService.java
src/main/java/com/sparta/mypet/domain/report/ReportController.java
src/main/java/com/sparta/mypet/domain/report/ReportRepository.java
src/main/java/com/sparta/mypet/domain/report/ReportService.java
src/main/java/com/sparta/mypet/domain/report/dto/ReportRequestDto.java
src/main/java/com/sparta/mypet/domain/report/dto/ReportResponseDto.java
src/main/java/com/sparta/mypet/domain/report/entity/Report.java

#32 
로그인한 유저가 다른 유저를 신고하는 기능 구현 (신고 생성하기 기능)
>
응답 데이터로 reportedUserId와 reporterUserId를 받고 있는데, userId보다는 email이나 nickname이 나을까요?

[2024/07/24]feat/#32 create report user

---

src/main/java/com/sparta/mypet/domain/petcare/dto/PetFacilityDto.java

[2024/07/25]fix/#62 Dto 오류 수정

---

http/backoffice.http
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
src/main/java/com/sparta/mypet/domain/backoffice/dto/UserListResponseDto.java
src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java

#53 
백오피스 전체 사용자 목록 조회 기능 추가
>

[2024/07/25]feat/#53 backoffice userList

---

http/backoffice.http
http/http-client.env.json
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
src/main/java/com/sparta/mypet/domain/backoffice/dto/UserStatusRequestDto.java
src/main/java/com/sparta/mypet/domain/backoffice/dto/UserStatusResponseDto.java

[2024/07/25]feat/#54 user status edit

---

http/backoffice.http
src/main/java/com/sparta/mypet/domain/auth/entity/User.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
src/main/java/com/sparta/mypet/domain/backoffice/dto/UserRoleRequestDto.java
src/main/java/com/sparta/mypet/domain/backoffice/dto/UserRoleResponseDto.java
src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java

#55 
유저 권한 변경 기능 추가
- 유저 권한은 admin 권한을 가진 유저만 변경할 수 있도록 함.
- 
>

[2024/07/25]feat/#55 user role edit

---

src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/common/exception/custom/InvalidCategoryException.java
src/main/java/com/sparta/mypet/domain/post/PostController.java
src/main/java/com/sparta/mypet/domain/post/PostService.java
src/main/java/com/sparta/mypet/domain/post/entity/Category.java
src/main/java/com/sparta/mypet/domain/s3/FileService.java

> ex) #66 
> files.size() 매직넘버 변경
> 두개로 구별되는 조건 삼항 연산자로 변경
> createPost 파일 개수 검사 코드 위치 변경
> getPosts Switch문 Enum을 사용하도록 변경
> uploadFile 향상된 For문 -> 일반 For문으로 변경
> deleteFile 메소드명 deleteFiles로 변경
> 리팩토링 pr인 만큼 보완하면 좋을 점 있으면 날카롭게 알려주세요..!

 [2024/07/25]refactor/#66 post file refactor

---

http/backoffice.http
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
src/main/java/com/sparta/mypet/domain/backoffice/dto/ReportListResponseDto.java
src/main/java/com/sparta/mypet/domain/report/ReportService.java

[2024/07/26]feat/#56 report list

---

http/backoffice.http
http/http-client.env.json
src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/common/exception/custom/ReportNotFoundException.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
src/main/java/com/sparta/mypet/domain/backoffice/dto/ReportStatusRequestDto.java
src/main/java/com/sparta/mypet/domain/report/ReportService.java
src/main/java/com/sparta/mypet/domain/report/entity/Report.java

[2024/07/26]feat/#57 report status edit

---

src/main/java/com/sparta/mypet/domain/auth/AuthController.java
src/main/java/com/sparta/mypet/domain/auth/AuthService.java
src/main/java/com/sparta/mypet/domain/auth/dto/LoginResponseDto.java
src/main/java/com/sparta/mypet/domain/auth/entity/User.java

#71 
로그인 응답 데이터 변경
>
User 객체의 변경이 있습니다! 오류가 발생하지 않으려면 DB의 User 테이블을 한번 날리고 실행하시면 됩니다!

[2024/07/26]refactor/#71 login response

---

src/main/java/com/sparta/mypet/domain/post/PostController.java

> ex) #77
> file -> files로 변경되었습니다.

[2024/07/26]fix/#77 post create fix

---

src/main/java/com/sparta/mypet/domain/auth/AuthController.java
src/main/java/com/sparta/mypet/domain/auth/AuthService.java
src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java

#76 
프론트 서버로 전달되는  `Authorization` 헤더가  cors 정책을 통과하도록 코드 수정
>

[2024/07/28]fix/#76 login to front

---

http/post.http
src/main/java/com/sparta/mypet/domain/post/PostController.java
src/main/java/com/sparta/mypet/domain/post/PostService.java

 [2024/07/28]fix/#80 post get islikepost

---

docker-compose.yml

#82 
도커 컴포즈 mysql 버전 8.0으로 변경했습니다.
>
docker 컨테이너 삭제하고 docker-compose up -d 하시면됩니다.

[2024/07/29] chore/#82 docker compose mysql

---

src/main/java/com/sparta/mypet/domain/post/dto/PostResponseDto.java

[2024/07/26]refactor/#85 postResponseDto postUserId

---

src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/domain/auth/AuthService.java
src/main/java/com/sparta/mypet/security/JwtService.java

#84 
refresh token 검증 로직 추가 및 이름 리펙토링
>

[2024/07/30]refactor/#84 auth refresh token

---

src/main/java/com/sparta/mypet/domain/auth/UserService.java
src/main/java/com/sparta/mypet/domain/auth/dto/UserWithPostListResponseDto.java

> #88
> 마이 페이지에 필요한 게시물 리스트 카테고리 별 5개씩 최신 글 순으로 가져오도록 수정

[2024/07/30]feat/#88 mypage post

---

src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/domain/auth/entity/UserRole.java
src/main/java/com/sparta/mypet/domain/post/PostService.java

> #90 
Admin, Manager에 사용자 게시물 삭제 권한 부여
UserRole 수정
PostService 수정
GlobalMessage 수정
>

[2024/07/30] fix/#90 Admin, Manager에 사용자 게시물 삭제 권한 부여

---

http/user.http
src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
src/main/java/com/sparta/mypet/common/exception/custom/UserNicknameDuplicateException.java
src/main/java/com/sparta/mypet/common/exception/custom/UserPasswordDuplicationException.java
src/main/java/com/sparta/mypet/domain/auth/UserController.java
src/main/java/com/sparta/mypet/domain/auth/UserService.java
src/main/java/com/sparta/mypet/domain/auth/dto/UserPasswordUpdateRequestDto.java
src/main/java/com/sparta/mypet/domain/auth/dto/UserUpdateRequestDto.java
src/main/java/com/sparta/mypet/domain/auth/dto/UserUpdateResponseDto.java
src/main/java/com/sparta/mypet/domain/auth/entity/User.java

#92 
- 회원 정보 수정 기능 => 현재는 닉네임만 수정 가능
- 회원 비밀번호 변경 기능
>

[2024/07/30]feat/#92 user update

---

src/main/java/com/sparta/mypet/domain/backoffice/dto/ReportListResponseDto.java

…serEmail
#96 
reportListDto의 reportedUserNickname을 email로 변경했습니다.
>

[2024/07/31]refactor/#96 reportListDto refactor

---

http/post.http

> #99
http 게시물 생성, 파일 업로드 테스트 기능 추가
>

[2024/07/31] refactor/#99 http 파일 업로드 테스트 기능 추가

---

http/post.http
src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/domain/post/PostController.java
src/main/java/com/sparta/mypet/domain/post/PostRepository.java
src/main/java/com/sparta/mypet/domain/post/PostService.java

#104 
> getPosts에 유저를 필터링 할 수 있는 파라미터가 추가되었습니다.

[2024/07/31] refactor/#104 getposts add parameter

---

http/report.http
src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/common/exception/custom/ReportDuplicationException.java
src/main/java/com/sparta/mypet/common/initialization/DataInitialization.java
src/main/java/com/sparta/mypet/domain/auth/AuthService.java
src/main/java/com/sparta/mypet/domain/auth/UserService.java
src/main/java/com/sparta/mypet/domain/auth/entity/User.java
src/main/java/com/sparta/mypet/domain/auth/entity/UserStatus.java
src/main/java/com/sparta/mypet/domain/backoffice/dto/ReportListResponseDto.java
src/main/java/com/sparta/mypet/domain/backoffice/dto/UserListResponseDto.java
src/main/java/com/sparta/mypet/domain/report/ReportController.java
src/main/java/com/sparta/mypet/domain/report/ReportRepository.java
src/main/java/com/sparta/mypet/domain/report/ReportService.java
src/main/java/com/sparta/mypet/domain/report/dto/ReportResponseDto.java
src/main/java/com/sparta/mypet/domain/report/entity/Report.java

#113 
- 신고 당한 유저와 맵핑에서 신고 당한 게시물과 맵핑으로 변경
- 유저 테이블에서 신고 관련된 항목 제거
>

[2024/08/01]refactor/#113 report mapping

---

src/main/java/com/sparta/mypet/domain/post/PostService.java

 [2024/08/02] refactor /#116 getposts

---

http/backoffice.http
src/main/java/com/sparta/mypet/domain/auth/entity/User.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
src/main/java/com/sparta/mypet/domain/backoffice/dto/SuspensionListResponseDto.java
src/main/java/com/sparta/mypet/domain/post/entity/Post.java
src/main/java/com/sparta/mypet/domain/suspension/SuspensionService.java

#102 
backoffice 정지목록 조회 기능 추가
>

[2024/08/02] feat/#102 backoffice suspension list

---

http/backoffice.http
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
src/main/java/com/sparta/mypet/domain/post/PostService.java

[2024/08/02]feat/#112 backoffice post list

---

http/backoffice.http
src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/common/exception/custom/PostStatusDuplicationException.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
src/main/java/com/sparta/mypet/domain/backoffice/dto/PostStatusRequestDto.java
src/main/java/com/sparta/mypet/domain/post/PostService.java

[2024/08/02]feat/#119 post status edit

---

build.gradle
src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/common/exception/custom/ReportStatusDuplicationException.java
src/main/java/com/sparta/mypet/common/exception/custom/UserInfoDuplicationException.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java

#122 
유저 상태, 역할 변경 / 신고 상태 변경시 동일 상태,역할로는 변경 안되도록 함.
>

[2024/08/02]fix/#122 duplication fix

---

src/main/java/com/sparta/mypet/domain/backoffice/dto/SuspensionListResponseDto.java

[2024/08/02]refactor/#125 suspensionResponseDto edit

---

src/main/java/com/sparta/mypet/domain/backoffice/dto/ReportListResponseDto.java

#127 
ReportListResponseDto category 컬럼 추가
>

[2024/08/02]refactor/#127 ReportListResponseDto add category

---

src/main/java/com/sparta/mypet/domain/backoffice/dto/ReportListResponseDto.java

#129 
reportListDto postUserId 추가
>

[2024/08/05]refactor/#129 reportList postUserId

---

src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
src/main/java/com/sparta/mypet/domain/post/PostController.java
src/main/java/com/sparta/mypet/domain/post/PostService.java
src/main/java/com/sparta/mypet/domain/post/dto/PostListResponseDto.java

#131 
기존 postResponseDto를
postListResponseDto / postListDto 2개로 분리

[2024/08/06]refactor/#131 PostListResponseDto detail

---

build.gradle
src/main/java/com/sparta/mypet/MypetApplication.java
src/main/java/com/sparta/mypet/common/config/RedisConfig.java
src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
src/main/java/com/sparta/mypet/common/exception/custom/SocialAccountLinkedException.java
src/main/java/com/sparta/mypet/common/util/ResponseFactory.java
src/main/java/com/sparta/mypet/domain/auth/UserService.java
src/main/java/com/sparta/mypet/domain/auth/dto/LoginResponseDto.java
src/main/java/com/sparta/mypet/domain/auth/dto/SignupRequestDto.java
src/main/java/com/sparta/mypet/domain/auth/dto/UserWithPostListResponseDto.java
src/main/java/com/sparta/mypet/domain/auth/entity/User.java
src/main/java/com/sparta/mypet/domain/feign/KakaoAuthApi.java
src/main/java/com/sparta/mypet/domain/feign/KakaoUserApi.java
src/main/java/com/sparta/mypet/domain/feign/config/FeignConfiguration.java
src/main/java/com/sparta/mypet/domain/oauth/KakaoAccountController.java
src/main/java/com/sparta/mypet/domain/oauth/KakaoAccountService.java
src/main/java/com/sparta/mypet/domain/oauth/SocialAccountController.java
src/main/java/com/sparta/mypet/domain/oauth/SocialAccountRepository.java
src/main/java/com/sparta/mypet/domain/oauth/SocialAccountService.java
src/main/java/com/sparta/mypet/domain/oauth/dto/KakaoAccountRequestDto.java
src/main/java/com/sparta/mypet/domain/oauth/dto/KakaoTokenResponseDto.java
src/main/java/com/sparta/mypet/domain/oauth/dto/KakaoUserInfoDto.java
src/main/java/com/sparta/mypet/domain/oauth/dto/SocialAccountResponse.java
src/main/java/com/sparta/mypet/domain/oauth/entity/SocialAccount.java
src/main/java/com/sparta/mypet/domain/oauth/entity/SocialAccountInfo.java
src/main/java/com/sparta/mypet/domain/oauth/entity/SocialAccountLeaveRequest.java
src/main/java/com/sparta/mypet/domain/oauth/entity/SocialType.java
src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java
src/main/resources/application.properties

[2024/08/07]feat/#70 kakao login

---

.github/workflows/aws.yml

aws.yml 파일 추가
> #134 
> aws.yml 파일 추가
> EC2 배포와 관련된 코드
>

[2024/08/07] githubAction 세팅

---

src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/domain/auth/UserService.java
src/main/java/com/sparta/mypet/domain/oauth/KakaoAccountController.java
src/main/java/com/sparta/mypet/domain/oauth/KakaoAccountService.java
src/main/java/com/sparta/mypet/domain/oauth/SocialAccountRepository.java
src/main/java/com/sparta/mypet/domain/oauth/SocialAccountService.java

> ex) #142
> 카카오 연동 해제 및 일반 회원 가입 문제 수정
>

[2024/08/07]fix/#142 kakao login bug

---

.github/workflows/aws.yml

> #144 
> distribution 필드가 누락된 부분 추가
>

[2024/08/08] 🩹 fix : distribution 필드가 누락된 부분 추가

---

.github/workflows/aws.yml

> #146 
> gradlew 파일 실행 권한 추가
>

[2024/08/08] 🩹 fix : gradlew 파일 실행 권한 추가

---

.github/workflows/aws.yml

[2024/08/08] fix : ec2 name 수정

---

.github/workflows/aws.yml

[2024/08/08] feat/#88 fix : 부분 수정

---

.github/workflows/aws.yml

[2024/08/08] fix : 부분 수정

---

.github/workflows/aws.yml

[2024/07/30] 🩹 fix : docker 추가

---

Dockerfile

[#146] 🎉 add : Dockerfile 추가

---

.github/workflows/aws.yml

[2024/08/08] fix : dockerHub 레포 이름 수정

---

.github/workflows/aws.yml

[2024/08/08] fix : dockerHub 레포 이름 부분수정

---

Dockerfile

> .env 파일 dockerContainer로 복사 코드 추가
>

[2024/08/08] fix : .env 파일 dockerContainer로 복사 코드 추가

---

Dockerfile

> .env 파일 dockerContainer로 복사 코드 수정
>

[2024/08/08] fix : .env 파일 dockerContainer로 복사 코드 수정

---

.github/workflows/aws.yml
Dockerfile

> .env 파일 전달방법 변경
> Dockerfile 에서 .env 관련 코드 삭제
> aws.yml 에 .env 관련 코드 추가
>

[2024/08/08] 🩹 fix: .env 파일 전달방법 변경

---

.github/workflows/aws.yml

> .env 파일 전달방법 변경
> yml 파일 일부 수정
>

[2024/08/08] 🩹 fix .env 파일 전달방법 변경

---

.github/workflows/aws.yml

> 인스턴스에 수동으로 .env 파일을 생성함에 따라
> .env 파일을 가져오는 코드를 삭제
>

[2024/08/08]🩹 fix .env 파일 관련 코드 삭제

---

.github/workflows/aws.yml

[2024/08/08] 🩹 fix .env 파일 관련 코드 삭제

---

build.gradle
http/email.http
src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
src/main/java/com/sparta/mypet/common/util/ResponseFactory.java
src/main/java/com/sparta/mypet/domain/mail/EmailService.java
src/main/java/com/sparta/mypet/domain/mail/EmailVerificationController.java
src/main/java/com/sparta/mypet/domain/mail/EmailVerificationService.java
src/main/java/com/sparta/mypet/domain/mail/config/MailConfig.java
src/main/java/com/sparta/mypet/domain/mail/dto/VerificationRequest.java
src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java
src/main/resources/application.properties
src/main/resources/templates/verification-email.html

> ex) #109
> 이메일 인증 기능
> 구글 SMTP를 사용해 메일 전송
>

[2024/08/08]Feat/#109 email verification

---

.github/workflows/aws.yml

[2024/08/09] 🩹 fix add-host 추가

---

.github/workflows/aws.yml

[2024/08/09] 🩹 fix add-host 일부 수정

---

http/backoffice.http
src/main/java/com/sparta/mypet/common/config/JPAConfig.java
src/main/java/com/sparta/mypet/domain/auth/UserRepository.java
src/main/java/com/sparta/mypet/domain/auth/UserRepositoryQuery.java
src/main/java/com/sparta/mypet/domain/auth/UserRepositoryQueryImpl.java
src/main/java/com/sparta/mypet/domain/auth/UserService.java
src/main/java/com/sparta/mypet/domain/auth/entity/UserSearchCondition.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
src/main/java/com/sparta/mypet/domain/backoffice/dto/UserListResponseDto.java

#168 
백오피스 유저리스트 - 이메일, 역할, 상태 검색기능 추가
>

[2024/08/09] feat/#168 backoffice userlist search

---

src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java

> #170 
> 도메인  http://www.petzoa.site, http://api.petzoa.site 추가했습니다.
> 테스트해보고 안되면 지울 예정....
>

[2024/08/11] 🩹 fix Cors 설정에 도메인 추가

---

src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java

> #170 
> http -> https 로 변경
>

[2024/08/08] fix : cors domain fix

---

http/post.http
src/main/java/com/sparta/mypet/domain/post/PostController.java
src/main/java/com/sparta/mypet/domain/post/PostService.java
src/main/java/com/sparta/mypet/domain/post/entity/PostStatus.java

#173 
HTTP메소드 DELETE -> PUT으로 변경됐습니다.
file, comment, like 정보가 모두 보존됩니다.

[2024/08/12]refactor/#173-post-soft-delete

---

src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java

[#170] 🩹 fix cors설정에 도메인 수정

---

.github/workflows/aws.yml

[#170] 🩹 fix 포트 수정

---

http/post.http
src/main/java/com/sparta/mypet/domain/auth/UserRepositoryQueryImpl.java
src/main/java/com/sparta/mypet/domain/post/PostController.java
src/main/java/com/sparta/mypet/domain/post/PostRepository.java
src/main/java/com/sparta/mypet/domain/post/PostRepositoryQueryImpl.java
src/main/java/com/sparta/mypet/domain/post/PostService.java
src/main/java/com/sparta/mypet/domain/post/dto/PostSearchCondition.java

#182 
일반 게시판 검색 기능 추가
>
backoffice와 같은 쿼리문을 사용하지만 front에서 조절할 예정입니다.

[2024/08/12]feat/#182 postList search

---

src/main/java/com/sparta/mypet/domain/post/PostService.java
src/main/java/com/sparta/mypet/domain/s3/FileService.java
src/main/java/com/sparta/mypet/domain/s3/ImageCompressionService.java
src/main/java/com/sparta/mypet/domain/s3/VideoCompressionService.java

#187
로직 분리
uploadFile ->  uploadFiles 메소드명 변경

[2024/08/12]refactor/#187 separate upload compression

---

src/main/java/com/sparta/mypet/domain/auth/dto/SignupRequestDto.java

#192 
회원가입 알림 세분화를 위해 중보되는 Vaild 메세지 삭제
>

[2024/08/13]fix/#192 signup alert

---

http/backoffice.http
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
src/main/java/com/sparta/mypet/domain/report/ReportRepository.java
src/main/java/com/sparta/mypet/domain/report/ReportRepositoryQuery.java
src/main/java/com/sparta/mypet/domain/report/ReportRepositoryQueryImpl.java
src/main/java/com/sparta/mypet/domain/report/ReportService.java
src/main/java/com/sparta/mypet/domain/report/dto/ReportSearchCondition.java

[2024/08/13]feat/#176 backoffice reportList search

---

http/backoffice.http
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
src/main/java/com/sparta/mypet/domain/suspension/SuspensionRepository.java
src/main/java/com/sparta/mypet/domain/suspension/SuspensionRepositoryQuery.java
src/main/java/com/sparta/mypet/domain/suspension/SuspensionRepositoryQueryImpl.java
src/main/java/com/sparta/mypet/domain/suspension/SuspensionService.java
src/main/java/com/sparta/mypet/domain/suspension/dto/SuspensionSearchCondition.java

#177 
백오피스 유저 정지 리스트 검색기능 추가
>

[2024/08/13]feat/#177 backoffice suspensionList search

---

src/main/java/com/sparta/mypet/common/util/ResponseFactory.java
src/main/java/com/sparta/mypet/domain/mail/EmailVerificationController.java
src/main/java/com/sparta/mypet/domain/mail/EmailVerificationService.java
src/main/java/com/sparta/mypet/domain/mail/dto/VerificationResponse.java

> #196
> 이메일 전송 Dto 변경
> 성공 실패 판단 변경
>

[2024/08/14]fix/#196 email verification

---

src/main/java/com/sparta/mypet/domain/s3/FileService.java
src/main/java/com/sparta/mypet/domain/s3/entity/FileContentType.java

[2024/08/14]refactor/#198 video logic refactor

---

http/report.http
src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
src/main/java/com/sparta/mypet/domain/post/PostRepository.java
src/main/java/com/sparta/mypet/domain/post/PostRepositoryQuery.java
src/main/java/com/sparta/mypet/domain/post/PostRepositoryQueryImpl.java
src/main/java/com/sparta/mypet/domain/post/PostService.java

#201 
- `findReportedPostIdsByUserId()` QueryDsl 적용
- `updatePostStatus()` QueryDsl 적용
>

[2024/08/18]refactor/#201 post querydsl
